"""crear tabla vehiculos

Revision ID: 97ac0e1b3269
Revises: 00ceabe6083a
Create Date: 2026-06-19 17:56:17.881030

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '97ac0e1b3269'
down_revision: Union[str, Sequence[str], None] = '00ceabe6083a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
